Add config object with validation and docstrings
WAM2layers/WAM2layers pull request #165
Opened 2022-12-02 12:52 UTC by Peter9192

closes #157

2022-12-22 07:58 UTC, Imme1992 commented
Great, thanks Peter, the explanation of the config file looks very good.
I have a few minor comments on the documentation.

Shall we put the target_frequency to 10min. I believe that is a better internal timestep to start with.
Periodic_boundary: Add there that this should be true when working with global data.

2022-12-22 08:01 UTC, Imme1992 approved these changes

2022-12-22 15:14 UTC, ruudvdent requested changes
Looks great, but I would be in favor to keep an updated example config file somewhere.

2022-12-23 09:17 UTC, Peter9192 commented
Thanks for the feedback Ruud! I will keep one `example-config.yaml` in the top folder. 

Looking again at it, I wonder whether we should

- Change the order of the options
- Remove options that are currently not available

2022-12-23 10:17 UTC, Peter9192 commented on docs/userguide.md
>  [here](https://github.com/WAM2layers/WAM2layers/blob/main/cases/era5_2021.yaml).
Well-spotted! Now updated with a new example-config file

2022-12-23 10:20 UTC, Peter9192 commented on docs/userguide.md
>  [here](https://github.com/WAM2layers/WAM2layers/blob/main/cases/era5_2021.yaml).
New link should work once this PR is merged

2022-12-23 10:31 UTC, ruudvdent approved these changes

2022-12-23 10:33 UTC, merged